name: dandylight
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.2.9+41

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.4
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  flutter_parallax: ^0.1.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_datetime_picker: ^1.5.1
  flare_flutter: ^3.0.2
  sembast: ^3.2.0
  equatable: ^2.0.3
  path_provider: ^2.0.10
  flutter_device_type: ^0.4.0
  url_launcher: ^6.0.5
  flutter_launcher_icons: ^0.12.0
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  google_maps_flutter: ^2.0.10
  android_intent_plus: ^3.1.1
  share_plus: ^6.3.0
  table_calendar: ^3.0.5
  flutter_rounded_date_picker: ^3.0.1
  flutter_circular_text: ^0.3.0
  flutter_cupertino_datetime_picker: ^3.0.0
  keyboard_actions: ^4.0.0
  keyboard_visibility: ^0.5.6
  geolocator: ^9.0.1
  flutter_speed_dial: ^6.0.0
  pdf: ^3.8.3
  flutter_full_pdf_viewer: ^1.0.6
  share_extend: ^2.0.0
  http: ^0.13.4
  flutter_google_places: ^0.3.0
  fluttertoast: ^8.0.9
  flutter_masked_text: ^0.8.0
  firebase_messaging: ^14.1.1
  uuid: ^3.0.6
  flutter_local_notifications: ^10.0.0
  rxdart: ^0.26.0
  geocoder: ^0.2.1
  app_settings: ^4.1.8
  device_calendar: ^4.2.0
  firebase_storage: ^11.0.6
  flutter_cache_manager: ^3.3.0
  loading_animation_widget: ^1.2.0+2
  fl_chart: ^0.55.1
  file_picker: ^5.1.0
  change_app_package_name: ^1.1.0
  flutter_app_badger: ^1.5.0
  flutter_native_timezone: ^2.0.0
  swipedetector: ^1.2.0
  flutter_share: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  mixpanel_flutter: ^2.0.0
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  showcaseview: ^2.0.0+1
  purchases_flutter: ^5.1.0
  super_banners: ^0.0.1
  synchronized: ^3.0.1
  sign_in_with_apple: ^4.3.0
  crypto: ^3.0.2
  google_sign_in: ^6.0.2
  pin_code_fields: ^7.4.0
  image: ^4.0.17
  cached_network_image: ^3.2.3
  url_launcher_web: ^2.0.18
  flutter_colorpicker: ^1.0.3
  image_cropper: ^4.0.1
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  firebase_crashlytics: ^3.3.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/dandy_light_app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#BCC6C0"
  adaptive_icon_foreground: "assets/images/app_icon_adaptive_android.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:

    - assets/images/dandy_light_app_icon.png
    - assets/images/dandy_light_logo_icon.png

    - assets/images/backgrounds/home_background_2.png
    - assets/images/backgrounds/home_background_3.png
    - assets/images/backgrounds/home_background_4.png
    - assets/images/backgrounds/image_background.png
    - assets/images/backgrounds/income_background_lighter.png
    - assets/images/backgrounds/expenses_background_lighter.png
    - assets/images/backgrounds/job_details_background.png
    - assets/images/backgrounds/expenses_background_peach.png
    - assets/images/backgrounds/login_background.png
    - assets/images/backgrounds/login_background_blue_mountain.png
    - assets/images/backgrounds/login_background_peach_dark_mountain.png
    - assets/images/backgrounds/login_background_peach_mountain.png
    - assets/images/backgrounds/login_background_sun.png

    - assets/images/instagram_logo_icon.png

    - assets/images/income_and_expenses/income_safe.png
    - assets/images/income_and_expenses/piggybank.png

    - assets/images/icons/trash_icon_peach.png
    - assets/images/icons/trash_icon_white.png
    - assets/images/icons/plus_icon_white.png
    - assets/images/icons/plus_icon_peach.png
    - assets/images/icons/contract_icon_peach.png
    - assets/images/icons/document_icon_peach.png
    - assets/images/icons/phone_icon_peach.png
    - assets/images/icons/sms_icon_peach.png
    - assets/images/icons/sms_icon_white.png
    - assets/images/icons/email_icon_peach.png
    - assets/images/icons/email_icon_white.png
    - assets/images/icons/instagram_icon_peach.png
    - assets/images/icons/instagram_icon_white.png
    - assets/images/icons/sunset_icon_peach.png
    - assets/images/icons/sunset_icon_white.png
    - assets/images/icons/edit_icon_peach.png
    - assets/images/icons/edit_icon_white.png
    - assets/images/icons/location_icon_peach.png
    - assets/images/icons/location_icon_white.png
    - assets/images/icons/calendar_icon_peach.png
    - assets/images/icons/calendar_icon_white.png
    - assets/images/icons/schedule_grey_dark.png
    - assets/images/icons/clock_icon_peach.png
    - assets/images/icons/price_package_icon.png
    - assets/images/icons/deposit_icon_peach.png
    - assets/images/icons/alert_icon_circle.png
    - assets/images/icons/contacts_icon.png
    - assets/images/icons/phonecall_icon_peach.png
    - assets/images/icons/phonecall_icon_white.png
    - assets/images/icons/job_stage_check_icon_white.png
    - assets/images/icons/settings_icon_white.png
    - assets/images/icons/word_of_mouth_icon_white.png
    - assets/images/icons/word_of_mouth_icon_peach.png
    - assets/images/icons/wordpress_icon_white.png
    - assets/images/icons/wordpress_icon_peach.png
    - assets/images/icons/website_icon_white.png
    - assets/images/icons/website_icon_peach.png
    - assets/images/icons/instagram_icon_peach_light.png
    - assets/images/icons/free_giveaway_icon_white.png
    - assets/images/icons/free_giveaway_icon_peach.png
    - assets/images/icons/facebook_icon_peach.png
    - assets/images/icons/facebook_icon_white.png
    - assets/images/icons/email_icon_peach_light.png
    - assets/images/icons/business_card_icon_peach.png
    - assets/images/icons/business_card_icon_white.png
    - assets/images/icons/briefcase_icon_white.png
    - assets/images/icons/briefcase_icon_peach_dark.png
    - assets/images/icons/dandy_light_icon_white.png
    - assets/images/icons/driving_directions_icon_blue.png
    - assets/images/icons/image_icon_blue.png
    - assets/images/icons/image_icon_white.png
    - assets/images/icons/camera_icon_white.png
    - assets/images/icons/driving_directions_icon_white.png
    - assets/images/icons/trash_icon_gold.png
    - assets/images/icons/trash_icon_blue.png
    - assets/images/icons/invoices_icon_white.png
    - assets/images/icons/drag_item_icon.png
    - assets/images/icons/pdf_icon_white.png
    - assets/images/icons/invoices_icon_peach.png
    - assets/images/icons/sunny_icon_gold.png
    - assets/images/icons/sunny_icon_white.png
    - assets/images/icons/very_cloudy_icon.png
    - assets/images/icons/lightning_rain_icon.png
    - assets/images/icons/cloudy_icon.png
    - assets/images/icons/sunny_rainy_icon.png
    - assets/images/icons/snowflake_icon.png
    - assets/images/icons/night_icon.png
    - assets/images/icons/rainy_icon.png
    - assets/images/icons/snowing_icon.png
    - assets/images/icons/hail_icon.png
    - assets/images/icons/cloudy_night_icon.png
    - assets/images/icons/partly_cloudy_icon.png
    - assets/images/icons/umbrella_icon.png
    - assets/images/icons/calendar_bold_black.png
    - assets/images/icons/calendar_bold_white.png
    - assets/images/icons/location_icon_black.png
    - assets/images/icons/collections_icon_white.png
    - assets/images/icons/expenses_icon_peach.png
    - assets/images/icons/coin_icon_peach.png
    - assets/images/icons/coins_icon_peach.png
    - assets/images/icons/charge_not_paid_icon_peach.png
    - assets/images/icons/charge_paid_icon_blue.png
    - assets/images/icons/start_icon_white.png
    - assets/images/icons/cancel_icon_white.png
    - assets/images/icons/cancel_icon_peach.png
    - assets/images/icons/driving_directions_icon_peach.png
    - assets/images/icons/facebook_icon_black.png
    - assets/images/icons/gmail_icon_black.png
    - assets/images/icons/reminder_icon_peach.png
    - assets/images/icons/reminder_icon_white.png
    - assets/images/icons/confirm_icon_gold.png
    - assets/images/icons/sign_out_icon_white.png
    - assets/images/icons/profile_icon_black.png
    - assets/images/icons/manage_subscription_icon_black.png
    - assets/images/icons/provide_feedback_icon_black.png
    - assets/images/icons/suggestions_icon_black.png
    - assets/images/icons/reminder_icon_blue_light.png
    - assets/images/icons/file_upload.png
    - assets/images/icons/signature.png
    - assets/images/icons/no_pictures.png
    - assets/images/icons/add_photo.png
    - assets/images/icons/trashcan.png
    - assets/images/icons/plus.png
    - assets/images/icons/bar_chart_icon.png
    - assets/images/icons/faq.png
    - assets/images/icons/question_mark.png
    - assets/images/icons/reminder_filled.png
    - assets/images/icons/price_package_black.png
    - assets/images/icons/permission_icon.png
    - assets/images/icons/profile_icon.png
    - assets/images/icons/pie_chart.png
    - assets/images/icons/windy.png
    - assets/images/icons/rainy_night.png
    - assets/images/icons/partly_cloudy_night.png
    - assets/images/icons/fog.png
    - assets/images/icons/clear_night.png
    - assets/images/icons/ribbon.png
    - assets/images/icons/trash.png
    - assets/images/icons/search.png
    - assets/images/icons/google.png
    - assets/images/icons/apple-logo.png
    - assets/images/icons/no_card.png
    - assets/images/icons/envelope.png
    - assets/images/icons/folder_storage.png
    - assets/images/icons/instagram_icon.png
    - assets/images/icons/image_review.png
    - assets/images/icons/rejected.png
    - assets/images/icons/no_wifi.png
    - assets/images/icons/art.png

    - assets/images/people/boy1.png
    - assets/images/people/boy2.png
    - assets/images/people/boy3.png
    - assets/images/people/boy4.png
    - assets/images/people/boy5.png
    - assets/images/people/boy6.png
    - assets/images/people/boy7.png
    - assets/images/people/boy8.png
    - assets/images/people/girl1.png
    - assets/images/people/girl2.png
    - assets/images/people/girl3.png
    - assets/images/people/girl4.png
    - assets/images/people/girl5.png
    - assets/images/people/girl6.png
    - assets/images/people/girl7.png
    - assets/images/people/girl8.png

    - assets/images/circle_black.png

    - assets/images/job_types/maternity.png
    - assets/images/job_types/engagement.png
    - assets/images/job_types/family_portrait.png
    - assets/images/job_types/newborn.png
    - assets/images/job_types/other.png
    - assets/images/job_types/wedding.png
    - assets/images/job_types/pet.png
    - assets/images/job_types/commercial_advertising.png
    - assets/images/job_types/modeling.png
    - assets/images/job_types/real_estate_architecture.png
    - assets/images/job_types/breastfeeding.png
    - assets/images/job_types/event.png
    - assets/images/job_types/nature.png
    - assets/images/job_types/anniversary.png
    - assets/images/job_types/birthday.png

    - assets/images/job_progress/check_mark.png
    - assets/images/job_progress/payment_requested.png
    - assets/images/job_progress/editing_complete.png
    - assets/images/job_progress/followup_sent.png
    - assets/images/job_progress/feedback_received.png
    - assets/images/job_progress/inquiry_received.png
    - assets/images/job_progress/planning_complete.png
    - assets/images/job_progress/proposal_sent.png
    - assets/images/job_progress/proposal_signed.png
    - assets/images/job_progress/gallery_sent.png
    - assets/images/job_progress/feedback_requested.png
    - assets/images/job_progress/feedback_received.png
    - assets/images/job_progress/session_complete.png
    - assets/images/job_progress/complete_check.png
    - assets/images/job_progress/payment_received.png
    - assets/images/job_progress/deposit_received.png
    - assets/images/job_progress/job_complete.png
    - assets/images/job_progress/white_check.png
    - assets/images/job_progress/undo.png

    - assets/images/lead_source_type/lead_source_blog.png
    - assets/images/lead_source_type/lead_source_business_card.png
    - assets/images/lead_source_type/lead_source_facebook.png
    - assets/images/lead_source_type/lead_source_giveaway.png
    - assets/images/lead_source_type/lead_source_instagram.png
    - assets/images/lead_source_type/lead_source_instagram_influencer.png
    - assets/images/lead_source_type/lead_source_other.png
    - assets/images/lead_source_type/lead_source_website.png
    - assets/images/lead_source_type/lead_source_word_of_mouth.png

    - assets/images/collection_icons/auto_responses_icon_white.png
    - assets/images/collection_icons/automation_icon_white.png
    - assets/images/collection_icons/contract_icon_white.png
    - assets/images/collection_icons/location_icon_white.png
    - assets/images/collection_icons/packages_icon_white.png
    - assets/images/collection_icons/poses_icon_white.png
    - assets/images/collection_icons/reminder_icon_white.png
    - assets/images/collection_icons/workflow_icon_white.png
    - assets/images/collection_icons/checklist_icon_white.png
    - assets/images/collection_icons/questionaire_icon_white.png

    - assets/images/collection_icons/pricing_profile_icons/money_stacks_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/coins_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/dollar_sign_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/coin_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/coin_stacks_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/piggy_bank_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/wallet_icon_gold.png
    - assets/images/collection_icons/pricing_profile_icons/money_bag_icon_gold.png

    - assets/images/collection_icons/pricing_profile_icons/money_stacks_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/coins_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/dollar_sign_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/coin_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/coin_stacks_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/piggy_bank_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/wallet_icon_white.png
    - assets/images/collection_icons/pricing_profile_icons/money_bag_icon_white.png
    - assets/images/collection_icons/location_pin_blue.png

    - assets/animations/success_check.flr

    - assets/images/backgrounds/image_background.png
    - assets/images/backgrounds/largebackground.png
    - assets/images/backgrounds/sample_brand.png
    - assets/images/backgrounds/flowerBgLaunch.png
    - assets/images/backgrounds/bannerImage.png
    - assets/images/calendar.png
    - assets/images/clock.png
    - assets/images/alert.png
    - assets/images/google_placeholder.jpeg

    - assets/images/reminders/camera.png
    - assets/images/reminders/welcome_hand.png

    - assets/images/menu/home_icon.png
    - assets/images/menu/jobs_icon.png
    - assets/images/menu/collections_icon.png
    - assets/images/menu/money_icon.png
    - assets/images/menu/sunset_icon.png

    -

  fonts:
    - family: Signature2
      fonts:
        - asset: assets/fonts/signature.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
    - family: Signature1
      fonts:
        - asset: assets/fonts/sig.ttf
    - family: simple
      fonts:
        - asset: assets/fonts/simplicity.ttf