// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC36wpexxKcYDz5-AAoa_opkEVHoPNurW8',
    appId: '1:43963046767:web:0f244a8e4e34720185e69a',
    messagingSenderId: '43963046767',
    projectId: 'clientsafe-21962',
    authDomain: 'clientsafe-21962.firebaseapp.com',
    databaseURL: 'https://clientsafe-21962.firebaseio.com',
    storageBucket: 'clientsafe-21962.appspot.com',
    measurementId: 'G-WB4Y5GK7CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFEEmUrk9E7lagg9cam_RI3zJ9cQkeYGU',
    appId: '1:43963046767:android:97b3ebdd3c14914e85e69a',
    messagingSenderId: '43963046767',
    projectId: 'clientsafe-21962',
    databaseURL: 'https://clientsafe-21962.firebaseio.com',
    storageBucket: 'clientsafe-21962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bgAEemGC3oUrDfp8FB8XQFfcuu_Hsng',
    appId: '1:43963046767:ios:a7f7c7e564a6577585e69a',
    messagingSenderId: '43963046767',
    projectId: 'clientsafe-21962',
    databaseURL: 'https://clientsafe-21962.firebaseio.com',
    storageBucket: 'clientsafe-21962.appspot.com',
    androidClientId: '43963046767-cb9om1s4gcncjirv3nbnls9s4spda7cb.apps.googleusercontent.com',
    iosClientId: '43963046767-bkqnqki8giamdfut41bdtg736cc9qs8c.apps.googleusercontent.com',
    iosBundleId: 'com.dandylight.mobile',
  );
}
